"""
Django settings for bou_routines_generator project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b-if3o=y*c-ky+9()7b(0^)61^bg3@rk1fm+s+*bo@9q!#l=d)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '0.0.0.0', 'testserver']


# Application definition

INSTALLED_APPS = [
    'bou_routines_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bou_routines_app.middleware.TeacherAccessMiddleware',
    'bou_routines_app.middleware.OfficeStaffAccessMiddleware',
]

ROOT_URLCONF = 'bou_routines_generator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bou_routines_app.context_processors.impersonation',
            ],
        },
    },
]

WSGI_APPLICATION = 'bou_routines_generator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# SQLite lock mitigation without WAL (no db.sqlite3-wal / db.sqlite3-shm):
# - Absolute NAME so every worker uses one file (optional BOU_SQLITE_PATH).
# - connect timeout + per-connection PRAGMAs in bou_routines_app.apps (DELETE journal, busy_timeout).
_sqlite_raw = (os.environ.get('BOU_SQLITE_PATH') or '').strip()
if _sqlite_raw:
    _sqlite_path = Path(_sqlite_raw).expanduser()
    if not _sqlite_path.is_absolute():
        _sqlite_path = (BASE_DIR / _sqlite_path).resolve()
    else:
        _sqlite_path = _sqlite_path.resolve()
else:
    _sqlite_path = (BASE_DIR / 'db.sqlite3').resolve()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(_sqlite_path),
        'OPTIONS': {
            'timeout': 60,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication backends - allow login with username or email
AUTHENTICATION_BACKENDS = [
    'bou_routines_app.backends.EmailOrUsernameModelBackend',  # Custom backend for email/username login
    'django.contrib.auth.backends.ModelBackend',  # Default backend as fallback
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.bousst.edu.bd'
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Use SSL for port 465
EMAIL_HOST_USER = 'support@bousst.edu.bd'
EMAIL_HOST_PASSWORD = 'LnSeXN?V=[2hBc&%'
DEFAULT_FROM_EMAIL = 'support@bousst.edu.bd'
SERVER_EMAIL = 'support@bousst.edu.bd'
