# Generated by Django 4.2.20 on 2025-04-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0003_alter_course_id_alter_currentroutine_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.teacher')),
            ],
            options={
                'unique_together': {('semester', 'course')},
            },
        ),
    ]
