# Generated by Django 4.2.20 on 2025-05-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0006_remove_semestercourse_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentroutine',
            name='teacher',
        ),
    ]
