# Generated by Django 4.2.20 on 2025-05-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0007_remove_currentroutine_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newroutine',
            options={'ordering': ['class_date', 'start_time']},
        ),
    ]
