# Generated by Django 4.2.20 on 2025-05-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0008_alter_newroutine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='lunch_break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='lunch_break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
