# Generated by Django 4.2.20 on 2025-05-18 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0009_semester_lunch_break_end_semester_lunch_break_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newroutine',
            name='teacher',
        ),
    ]
