# Generated by Django 4.2.20 on 2025-05-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0010_remove_newroutine_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='date_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
