# Generated by Django 4.2.20 on 2025-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0012_remove_semester_date_range_semester_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='holidays',
            field=models.TextField(blank=True, help_text='Comma-separated list of holiday dates (YYYY-MM-DD)', null=True),
        ),
    ]
