# Generated by Django 4.2.20 on 2025-06-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0013_semester_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='number_of_classes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
