# Generated by Django 4.2.20 on 2025-07-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0015_semester_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
