# Generated by Django 4.2.20 on 2025-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0016_teacher_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for semester dropdown'),
        ),
    ]
