# Generated by Django 4.2.20 on 2025-07-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0018_alter_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newroutine',
            options={},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='currentroutine',
            unique_together={('course', 'semester')},
        ),
        migrations.AddIndex(
            model_name='currentroutine',
            index=models.Index(fields=['semester', 'day'], name='bou_routine_semeste_5eca04_idx'),
        ),
        migrations.AddIndex(
            model_name='currentroutine',
            index=models.Index(fields=['day', 'start_time'], name='bou_routine_day_a89432_idx'),
        ),
        migrations.AddIndex(
            model_name='newroutine',
            index=models.Index(fields=['semester', 'class_date'], name='bou_routine_semeste_ea8ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='newroutine',
            index=models.Index(fields=['course', 'semester'], name='bou_routine_course__56b5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='newroutine',
            index=models.Index(fields=['class_date', 'start_time'], name='bou_routine_class_d_091a84_idx'),
        ),
        migrations.AddIndex(
            model_name='semestercourse',
            index=models.Index(fields=['semester'], name='bou_routine_semeste_1b7cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='semestercourse',
            index=models.Index(fields=['course'], name='bou_routine_course__34a4c0_idx'),
        ),
    ]
