# Generated by Django 4.2.20 on 2025-07-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0019_alter_newroutine_options_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currentroutine',
            unique_together=set(),
        ),
    ]
