# Generated by Django 4.2.20 on 2025-07-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0020_alter_currentroutine_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newroutine',
            options={'ordering': ['class_date', 'start_time']},
        ),
        migrations.RemoveIndex(
            model_name='currentroutine',
            name='bou_routine_semeste_5eca04_idx',
        ),
        migrations.RemoveIndex(
            model_name='currentroutine',
            name='bou_routine_day_a89432_idx',
        ),
        migrations.RemoveIndex(
            model_name='newroutine',
            name='bou_routine_semeste_ea8ab6_idx',
        ),
        migrations.RemoveIndex(
            model_name='newroutine',
            name='bou_routine_course__56b5a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='newroutine',
            name='bou_routine_class_d_091a84_idx',
        ),
        migrations.RemoveIndex(
            model_name='semestercourse',
            name='bou_routine_semeste_1b7cb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='semestercourse',
            name='bou_routine_course__34a4c0_idx',
        ),
        migrations.AddField(
            model_name='semester',
            name='makeup_dates',
            field=models.TextField(blank=True, help_text='Comma-separated list of makeup/extra class dates (YYYY-MM-DD)', null=True),
        ),
    ]
