# Generated by Django 4.2.20 on 2025-07-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0021_add_makeup_dates'),
    ]

    operations = [
    ]
