# Generated by Django 4.2.20 on 2025-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0022_auto_20250712_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='lab_class_duration_minutes',
            field=models.PositiveIntegerField(default=90, help_text='Duration of lab classes in minutes (default: 90)'),
        ),
        migrations.AddField(
            model_name='semester',
            name='theory_class_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Duration of theory classes in minutes (default: 60)'),
        ),
    ]
