# Generated by Django 4.2.20 on 2025-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0023_semester_lab_class_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='teacher_short_name_newline',
            field=models.BooleanField(default=True, help_text="Show teacher's short name on a new line in PDF routine table (otherwise, show on same line as course code)"),
        ),
    ]
