# Generated by Django 4.2.20 on 2025-10-11 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0025_loginlog'),
    ]

    operations = [
        # Create Curriculum model
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Curriculum name (e.g., 'Current Curriculum', 'New Curriculum 2024')", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short code for curriculum (e.g., 'CURR', 'NEW2024')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the curriculum', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this curriculum is currently active')),
                ('effective_from', models.DateField(blank=True, help_text='Date from which this curriculum is effective', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'ordering': ['-is_active', 'name'],
            },
        ),
        
        # Add curriculum field to Course model
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='Curriculum this course belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.curriculum'),
        ),
        
        # Add curriculum-specific fields to Course model
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=3, help_text='Number of credits for this course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_theory',
            field=models.BooleanField(default=True, help_text='Whether this is a theory course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_lab',
            field=models.BooleanField(default=False, help_text='Whether this is a lab course'),
        ),
        
        # Add CA distribution fields
        migrations.AddField(
            model_name='course',
            name='ca_attendance_weight',
            field=models.PositiveIntegerField(default=10, help_text='CA weight for attendance (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='ca_assignment_weight',
            field=models.PositiveIntegerField(default=20, help_text='CA weight for assignments (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='ca_quiz_weight',
            field=models.PositiveIntegerField(default=20, help_text='CA weight for quizzes (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='ca_midterm_weight',
            field=models.PositiveIntegerField(default=50, help_text='CA weight for midterm (%)'),
        ),
        
        # Add lab-specific CA distribution fields
        migrations.AddField(
            model_name='course',
            name='lab_ca_attendance_weight',
            field=models.PositiveIntegerField(default=10, help_text='Lab CA weight for attendance (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_ca_assignment_weight',
            field=models.PositiveIntegerField(default=30, help_text='Lab CA weight for assignments (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_ca_practical_weight',
            field=models.PositiveIntegerField(default=60, help_text='Lab CA weight for practical exams (%)'),
        ),
        
        # Add course type and prerequisite fields
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('GENERAL', 'General'), ('PROJECT', 'Project')], default='CORE', help_text='Type of course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, help_text='Prerequisite courses', related_name='prerequisite_for', to='bou_routines_app.course'),
        ),
        
        # Add timestamp fields to Course
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add curriculum field to Semester
        migrations.AddField(
            model_name='semester',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='Curriculum this semester follows', null=True, on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.curriculum'),
        ),
        
        # Update Course model constraints
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'curriculum')},
        ),
        
        # Update Course model ordering
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['curriculum', 'code']},
        ),
    ]
