# Generated by Django 4.2.20 on 2025-09-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0025_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(help_text='Student ID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(help_text='Academic session (e.g., 2020-21)', max_length=20)),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.semester')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(choices=[('attendance', 'Class Attendance'), ('ca', 'Continuous Assessment'), ('final_marks', 'Semester Final Marks')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'ability')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.course')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.student')),
            ],
            options={
                'ordering': ['attendance_date', 'student__id'],
                'unique_together': {('student', 'course', 'semester', 'attendance_date')},
            },
        ),
    ]
