# Generated by Django 4.2.20 on 2025-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0026_add_curriculum_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, help_text='Prerequisite courses', to='bou_routines_app.course'),
        ),
    ]
