# Generated by Django 4.2.20 on 2025-09-23 23:01

from django.db import migrations, models


def migrate_semester_data(apps, schema_editor):
    """
    Migrate existing semester ForeignKey data to the new ManyToManyField
    """
    Student = apps.get_model('bou_routines_app', 'Student')
    
    # Get all students and their current semester
    for student in Student.objects.all():
        if hasattr(student, 'semester') and student.semester:
            # Add the existing semester to the new ManyToManyField
            student.semesters.add(student.semester)


def reverse_migrate_semester_data(apps, schema_editor):
    """
    Reverse migration: get the first semester from ManyToManyField and set it as ForeignKey
    Note: This will only work if students have exactly one semester
    """
    Student = apps.get_model('bou_routines_app', 'Student')
    
    for student in Student.objects.all():
        semesters = student.semesters.all()
        if semesters.exists():
            # Take the first semester (this might not be ideal for reverse migration)
            student.semester = semesters.first()
            student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0027_alter_teacher_options_teacher_address_and_more'),
    ]

    operations = [
        # First, add the new ManyToManyField (without removing the old one yet)
        migrations.AddField(
            model_name='student',
            name='semesters',
            field=models.ManyToManyField(help_text='Semesters this student is enrolled in', to='bou_routines_app.semester', blank=True),
        ),
        
        # Migrate the data from old field to new field
        migrations.RunPython(migrate_semester_data, reverse_migrate_semester_data),
        
        # Now remove the old ForeignKey field
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
