# Generated by Django 4.2.20 on 2025-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0027_update_semester_unique_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['curriculum', 'order', 'name']},
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'curriculum')},
        ),
    ]
