# Generated by Django 4.2.20 on 2025-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0028_update_semester_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'curriculum')},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'curriculum'), ('name', 'curriculum')},
        ),
    ]
