# Generated by Django 4.2.20 on 2025-10-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0028_student_multiple_semesters'),
        ('bou_routines_app', '0029_alter_course_unique_together_alter_course_name_and_more'),
    ]

    operations = [
    ]
