# Generated by Django 4.2.20 on 2025-10-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0030_merge_20251011_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='code',
            field=models.CharField(help_text="Short code for curriculum (e.g., 'OLD', 'NEW2024')", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semesters',
            field=models.ManyToManyField(help_text='Semesters this student is enrolled in', to='bou_routines_app.semester'),
        ),
        migrations.CreateModel(
            name='CAMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_mark', models.DecimalField(decimal_places=2, default=0, help_text='Attendance mark (auto-calculated)', max_digits=5)),
                ('assignment_mark', models.DecimalField(decimal_places=2, default=0, help_text='Assignment mark', max_digits=5)),
                ('quiz_mark', models.DecimalField(decimal_places=2, default=0, help_text='Quiz mark', max_digits=5)),
                ('midterm_mark', models.DecimalField(decimal_places=2, default=0, help_text='Midterm mark', max_digits=5)),
                ('lab_assignment_mark', models.DecimalField(decimal_places=2, default=0, help_text='Lab assignment mark', max_digits=5)),
                ('lab_practical_mark', models.DecimalField(decimal_places=2, default=0, help_text='Lab practical mark', max_digits=5)),
                ('total_ca_mark', models.DecimalField(decimal_places=2, default=0, help_text='Total CA mark', max_digits=5)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.course')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.student')),
            ],
            options={
                'ordering': ['student__id'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
