# Generated by Django 4.2.20 on 2025-10-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0031_alter_curriculum_code_alter_student_semesters_camark'),
    ]

    operations = [
        migrations.AddField(
            model_name='camark',
            name='first_assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='First Assignment/Presentation mark', max_digits=5),
        ),
        migrations.AddField(
            model_name='camark',
            name='second_assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Second Assignment/Presentation mark', max_digits=5),
        ),
        migrations.AddField(
            model_name='camark',
            name='third_assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Third Assignment/Presentation mark', max_digits=5),
        ),
        migrations.AlterField(
            model_name='camark',
            name='assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average Assignment mark (auto-calculated)', max_digits=5),
        ),
    ]
