# Generated by Django 4.2.20 on 2025-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0032_add_assignment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='camark',
            name='first_lab_assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='First Lab Assignment/Report mark', max_digits=5),
        ),
        migrations.AddField(
            model_name='camark',
            name='second_lab_assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Second Lab Assignment/Report mark', max_digits=5),
        ),
        migrations.AddField(
            model_name='camark',
            name='third_lab_assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Third Lab Assignment/Report mark', max_digits=5),
        ),
        migrations.AlterField(
            model_name='camark',
            name='lab_assignment_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average Lab Assignment mark (auto-calculated)', max_digits=5),
        ),
    ]
