# Generated by Django 4.2.20 on 2025-12-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0033_camark_first_lab_assignment_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher1_q1', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 1 - Question Set 1 (max 14)', max_digits=5, null=True)),
                ('teacher1_q2', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 1 - Question Set 2 (max 14)', max_digits=5, null=True)),
                ('teacher1_q3', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 1 - Question Set 3 (max 14)', max_digits=5, null=True)),
                ('teacher1_q4', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 1 - Question Set 4 (max 14)', max_digits=5, null=True)),
                ('teacher1_q5', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 1 - Question Set 5 (max 14)', max_digits=5, null=True)),
                ('teacher1_q6', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 1 - Question Set 6 (max 14)', max_digits=5, null=True)),
                ('teacher1_q7', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 1 - Question Set 7 (max 14)', max_digits=5, null=True)),
                ('teacher1_total', models.DecimalField(decimal_places=2, default=0, help_text='Teacher 1 total (auto-calculated, max 70)', max_digits=5)),
                ('teacher2_q1', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 2 - Question Set 1 (max 14)', max_digits=5, null=True)),
                ('teacher2_q2', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 2 - Question Set 2 (max 14)', max_digits=5, null=True)),
                ('teacher2_q3', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 2 - Question Set 3 (max 14)', max_digits=5, null=True)),
                ('teacher2_q4', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 2 - Question Set 4 (max 14)', max_digits=5, null=True)),
                ('teacher2_q5', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 2 - Question Set 5 (max 14)', max_digits=5, null=True)),
                ('teacher2_q6', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 2 - Question Set 6 (max 14)', max_digits=5, null=True)),
                ('teacher2_q7', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 2 - Question Set 7 (max 14)', max_digits=5, null=True)),
                ('teacher2_total', models.DecimalField(decimal_places=2, default=0, help_text='Teacher 2 total (auto-calculated, max 70)', max_digits=5)),
                ('teacher3_q1', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 3 - Question Set 1 (max 14)', max_digits=5, null=True)),
                ('teacher3_q2', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 3 - Question Set 2 (max 14)', max_digits=5, null=True)),
                ('teacher3_q3', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 3 - Question Set 3 (max 14)', max_digits=5, null=True)),
                ('teacher3_q4', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 3 - Question Set 4 (max 14)', max_digits=5, null=True)),
                ('teacher3_q5', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 3 - Question Set 5 (max 14)', max_digits=5, null=True)),
                ('teacher3_q6', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 3 - Question Set 6 (max 14)', max_digits=5, null=True)),
                ('teacher3_q7', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Teacher 3 - Question Set 7 (max 14)', max_digits=5, null=True)),
                ('teacher3_total', models.DecimalField(decimal_places=2, default=0, help_text='Teacher 3 total (auto-calculated, max 70)', max_digits=5)),
                ('lab_final_exam_mark', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lab course final exam mark (max 60)', max_digits=5, null=True)),
                ('final_exam_total', models.DecimalField(decimal_places=2, default=0, help_text='Final exam total mark', max_digits=5)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requires_third_teacher', models.BooleanField(default=False, help_text='True if difference between teacher1 and teacher2 > 20% or > 14 marks')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.course')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_marks_marked_by', to='bou_routines_app.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.student')),
                ('teacher1_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_marks_teacher1', to='bou_routines_app.teacher')),
                ('teacher2_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_marks_teacher2', to='bou_routines_app.teacher')),
                ('teacher3_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_marks_teacher3', to='bou_routines_app.teacher')),
            ],
            options={
                'ordering': ['student__id'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
