# Generated by Django 4.2.20 on 2025-12-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0034_finalexammark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Centre name (e.g., 'DRC Centre', 'DUET Centre')", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short code for centre (e.g., 'DRC', 'DUET')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the centre', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this centre is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': 'Centres',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Centre this semester belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bou_routines_app.centre'),
        ),
        migrations.AddField(
            model_name='student',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Centre this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bou_routines_app.centre'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Centre this teacher belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bou_routines_app.centre'),
        ),
    ]
