# Generated by Django 4.2.20 on 2025-12-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0037_make_centre_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='study_center',
        ),
    ]
