# Generated by Django 4.2.20 on 2025-12-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0038_remove_study_center_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'curriculum', 'centre')},
        ),
    ]
