# Generated by Django 4.2.20 on 2025-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0039_update_semester_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='contact_person_secondary_designation',
            field=models.CharField(blank=True, help_text='Secondary designation for the contact person', max_length=100, null=True),
        ),
    ]
