# Generated by Django 4.2.20 on 2025-12-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0042_add_student_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher for this course in this specific semester/centre. If not set, uses course.teacher as fallback.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bou_routines_app.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Default teacher for this course. Can be overridden per semester/centre via SemesterCourse.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bou_routines_app.teacher'),
        ),
    ]
