# Generated by Django 4.2.20 on 2025-12-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0044_populate_semestercourse_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
