# Generated by Django 4.2.20 on 2025-12-01 20:38

from django.db import migrations, models
import django.db.models.deletion
from collections import defaultdict


def delete_duplicate_semesters_before_constraint_change(apps, schema_editor):
    """Delete duplicate semesters (DUET) before changing unique constraint"""
    Semester = apps.get_model('bou_routines_app', 'Semester')
    SemesterCourse = apps.get_model('bou_routines_app', 'SemesterCourse')
    
    # Group semesters by name and curriculum
    semester_groups = defaultdict(list)
    for semester in Semester.objects.all().order_by('id'):
        key = (semester.name, semester.curriculum_id if semester.curriculum else None)
        semester_groups[key].append(semester)
    
    # For each group with duplicates, keep the first (lowest ID) and move SemesterCourse records, then delete duplicates
    deleted_count = 0
    moved_count = 0
    
    for key, semesters in semester_groups.items():
        if len(semesters) > 1:
            # Sort by ID to ensure we keep the original (lowest ID)
            semesters.sort(key=lambda s: s.id)
            first_semester = semesters[0]  # Keep this one (original DRC semester)
            
            # Process duplicates (DUET semesters)
            for duplicate_semester in semesters[1:]:
                # Get all SemesterCourse records for this duplicate semester
                duplicate_scs = SemesterCourse.objects.filter(semester=duplicate_semester)
                
                for sc in duplicate_scs:
                    # Check if a SemesterCourse already exists for first_semester + course
                    existing_sc = SemesterCourse.objects.filter(
                        semester=first_semester,
                        course=sc.course
                    ).first()
                    
                    if existing_sc:
                        # Update existing one with teacher if duplicate has one
                        if sc.teacher and not existing_sc.teacher:
                            existing_sc.teacher = sc.teacher
                            existing_sc.save()
                        # Delete the duplicate
                        sc.delete()
                    else:
                        # Move to first semester
                        sc.semester = first_semester
                        sc.save()
                        moved_count += 1
                
                # Delete the duplicate semester
                duplicate_semester.delete()
                deleted_count += 1
    
    print(f"Pre-migration: Deleted {deleted_count} duplicate (DUET) semesters, moved {moved_count} SemesterCourse records")


def reverse_delete_duplicates(apps, schema_editor):
    """Reverse migration - not fully reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0045_remove_teacher_from_course'),
    ]

    operations = [
        # First, delete duplicate semesters before changing unique constraint
        migrations.RunPython(delete_duplicate_semesters_before_constraint_change, reverse_delete_duplicates),
        migrations.AlterUniqueTogether(
            name='semestercourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Study Centre this course is offered in for this semester (required)', null=True, on_delete=django.db.models.deletion.PROTECT, to='bou_routines_app.centre'),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher for this course in this specific semester/centre.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bou_routines_app.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'curriculum')},
        ),
        migrations.AlterUniqueTogether(
            name='semestercourse',
            unique_together={('semester', 'course', 'centre')},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='centre',
        ),
    ]
