# Generated by Django 4.2.20 on 2025-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0047_migrate_centre_data_and_remove_duet_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='lab_ca_assignment_weight',
            field=models.PositiveIntegerField(default=10, help_text='Lab CA weight for assignments (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='lab_ca_attendance_weight',
            field=models.PositiveIntegerField(default=10, help_text='Lab CA weight for attendance (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='lab_ca_practical_weight',
            field=models.PositiveIntegerField(default=10, help_text='Lab CA weight for practical exams (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='lab_ca_quiz_weight',
            field=models.PositiveIntegerField(default=10, help_text='Lab CA weight for quizzes (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='project_evaluation_weight',
            field=models.PositiveIntegerField(default=40, help_text='Project evaluation weight (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='project_presentation_weight',
            field=models.PositiveIntegerField(default=30, help_text='Project presentation weight (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='project_supervisor_weight',
            field=models.PositiveIntegerField(default=30, help_text='Project supervisor weight (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='theory_ca_assignment_weight',
            field=models.PositiveIntegerField(default=10, help_text='Theory CA weight for assignments (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='theory_ca_attendance_weight',
            field=models.PositiveIntegerField(default=5, help_text='Theory CA weight for attendance (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='theory_ca_midterm_weight',
            field=models.PositiveIntegerField(default=0, help_text='Theory CA weight for midterm (%)'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='theory_ca_quiz_weight',
            field=models.PositiveIntegerField(default=15, help_text='Theory CA weight for quizzes (%)'),
        ),
    ]
