# Generated by Django 4.2.20 on 2026-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0049_camark_project_evaluation_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='mid_term_exam_dates',
            field=models.TextField(blank=True, help_text='Comma-separated list of mid-term exam dates (YYYY-MM-DD). Only used for new curriculum.', null=True),
        ),
    ]
