# Generated by Django 4.2.20 on 2026-01-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0051_add_student_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='hide_teacher_name_in_pdf',
            field=models.BooleanField(default=False, help_text="Hide teacher's name in PDF routine (both in routine table and Course Teacher column)"),
        ),
    ]
