# Generated by Django 4.2.20 on 2026-01-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0053_add_hide_teacher_name_in_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCentreCoordinator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(help_text='Study Centre this coordinator is assigned to', on_delete=django.db.models.deletion.PROTECT, to='bou_routines_app.centre')),
                ('program_coordinator', models.ForeignKey(help_text='Program Coordinator for this semester/centre', on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.programcoordinator')),
                ('semester', models.ForeignKey(help_text='Semester this coordinator is assigned to', on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.semester')),
            ],
            options={
                'verbose_name': 'Semester Centre Coordinator',
                'verbose_name_plural': 'Semester Centre Coordinators',
                'ordering': ['semester', 'centre'],
                'unique_together': {('semester', 'centre')},
            },
        ),
    ]
