# Generated by Django 4.2.20 on 2026-01-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0055_add_class_test_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camark',
            name='midterm_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Midterm mark (for new curriculum)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='camark',
            name='quiz_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quiz mark (deprecated - kept for database compatibility, always set to 0)', max_digits=5),
        ),
    ]
