# Generated by Django 4.2.20 on 2026-01-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0056_add_quiz_mark_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camark',
            name='quiz_mark',
        ),
    ]
