# Generated by Django 4.2.20 on 2026-01-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0057_remove_quiz_mark_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Term code (e.g., '251', '252')", max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Term name (optional)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this term is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='semester',
            name='term',
        ),
        migrations.AddField(
            model_name='semester',
            name='session_old_char',
            field=models.CharField(blank=True, db_column='session', help_text='DEPRECATED: Use session.name instead', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='term_old',
            field=models.CharField(blank=True, db_column='term', help_text='DEPRECATED: Use session.term.code instead', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Session name (e.g., '2024-2025', '2025-2026')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(help_text='Term associated with this session', on_delete=django.db.models.deletion.CASCADE, to='bou_routines_app.term')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-name'],
                'unique_together': {('name', 'term')},
            },
        ),
        migrations.AlterField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Academic session for this semester', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='bou_routines_app.session'),
        ),
    ]
