# Generated by Django 4.2.20 on 2026-01-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0058_term_remove_semester_term_semester_session_old_char_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semester',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term for this semester', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='bou_routines_app.term'),
        ),
        migrations.AddField(
            model_name='student',
            name='session_old',
            field=models.CharField(blank=True, db_column='session', help_text='DEPRECATED: Use session ForeignKey instead', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Academic term for this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bou_routines_app.term'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='session_old_char',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use session field instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='term_old',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use term field instead', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(help_text="Session name (e.g., '2024-2025', '2025-2026')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Academic session for this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='bou_routines_app.session'),
        ),
        migrations.RemoveField(
            model_name='session',
            name='term',
        ),
    ]
