# Generated by Django 4.2.20 on 2026-01-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0059_alter_session_unique_together_semester_term_and_more'),
    ]

    operations = [
    ]
