# Generated by Django 4.2.20 on 2026-04-26 11:11
#
# Reconciles the schema with models after 0063: drops the Session/Term models and
# transition fields from 0058-0059 (session_old, term_old, etc.) and uses CharField
# session/term on Semester and CharField session on Student.
#
# Apply after 0063. On a copy of a live database, run migrations in order; if the
# database schema was changed manually, you may need to `migrate --fake` specific
# steps that already match the database.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0063_semestercourse_attendance_midterm_override_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='session_old_char',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='term_old',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_old',
        ),
        migrations.RemoveField(
            model_name='student',
            name='term',
        ),
        migrations.AlterField(
            model_name='finalexammark',
            name='requires_third_teacher',
            field=models.BooleanField(default=False, help_text='True if absolute difference between teacher1 and teacher2 totals exceeds 14 marks'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(default='', help_text='Academic session (e.g., 2020-21)', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
