# Generated by Django 4.2

from django.db import migrations, models


def set_new_curriculum_lab_weights(apps, schema_editor):
    Curriculum = apps.get_model('bou_routines_app', 'Curriculum')
    for c in Curriculum.objects.exclude(code='OLD'):
        c.lab_ca_attendance_weight = 5
        c.lab_ca_assignment_weight = 5
        c.lab_ca_practical_weight = 15
        c.lab_ca_practical2_weight = 0
        c.save(
            update_fields=[
                'lab_ca_attendance_weight',
                'lab_ca_assignment_weight',
                'lab_ca_practical_weight',
                'lab_ca_practical2_weight',
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0064_remove_semester_session_old_char_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='lab_ca_practical2_weight',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Lab CA weight for second experiment / lab project column (0 = single column)',
            ),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_ca_practical2_weight',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Lab CA weight for second experiment column (0 = use single column)',
            ),
        ),
        migrations.AddField(
            model_name='camark',
            name='second_lab_practical_mark',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Second experiment / lab project mark (new curriculum split)',
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name='finalexammark',
            name='lab_viva_mark',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text='Lab viva (new curriculum only, max 5)',
                max_digits=5,
                null=True,
            ),
        ),
        migrations.RunPython(set_new_curriculum_lab_weights, noop_reverse),
    ]
