# Generated by Django 4.2.20 on 2026-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0067_lab_final_exam_per_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camark',
            name='lab_practical_mark',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lab practical / first experiment mark', max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='lab_ca_practical_weight',
            field=models.PositiveIntegerField(default=60, help_text='Lab CA weight for first experiment / lab project (%)'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='lab_ca_practical_weight',
            field=models.PositiveIntegerField(default=10, help_text='Lab CA weight for first experiment / lab project portion (%)'),
        ),
        migrations.AlterField(
            model_name='finalexammark',
            name='lab_final_exam_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lab course: denormalized avg problem solving / old curriculum (legacy readers)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='finalexammark',
            name='lab_viva_mark',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Lab viva: denormalized average (legacy readers)', max_digits=5, null=True),
        ),
    ]
