# Generated by Django 4.2.20 on 2026-07-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bou_routines_app', '0075_lab_chairman_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='lab_examination_member1',
            field=models.ForeignKey(blank=True, help_text='Lab viva examination member 1 (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_courses_as_lab_examination_member1', to='bou_routines_app.teacher'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='lab_examination_member2',
            field=models.ForeignKey(blank=True, help_text='Lab viva examination member 2 (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_courses_as_lab_examination_member2', to='bou_routines_app.teacher'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='lab_examination_member3',
            field=models.ForeignKey(blank=True, help_text='Lab viva examination member 3 (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_courses_as_lab_examination_member3', to='bou_routines_app.teacher'),
        ),
        migrations.AddField(
            model_name='semestercourse',
            name='lab_examination_member4',
            field=models.ForeignKey(blank=True, help_text='Lab viva examination member 4 (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_courses_as_lab_examination_member4', to='bou_routines_app.teacher'),
        ),
    ]
